- name: Install telegraf packages
  package:
    name: "{{ telegraf_distro_packages }}"
    state: "{{ telegraf_package_state }}"
    update_cache: "{{ (ansible_pkg_mgr == 'apt') | ternary('yes', omit) }}"
    cache_valid_time: "{{ (ansible_pkg_mgr == 'apt') | ternary(cache_timeout, omit) }}"
  register: install_packages
  until: install_packages | success
  retries: 5
  delay: 2
  tags:
    - install-apt
    - install-yum
    - install-zypper

